# settings3.yaml -- the basic setup of the test site

# goes into SiteLayout
siteLayout:
    themeDir:  /home/frank/Workspace11/ssg/docs/theme
    doughDir: /home/frank/Workspace11/ssg/docs/site/dough
    bakedDir: /home/frank/Workspace11/ssg/docs/site/baked
    reportFile: /home/frank/ssgReport.txt
    testDir: /home/frank/.ssg 
    # masterTemplateFile: master6.dtpl  #in themeDir
    masterTemplateFile: master7tufte.dtpl  #in themeDir
    # change is global for the site, not per page TODO?
    doNotPublish: "DNB"
    blogAuthorToSuppress: 
      - "AUF"
      - "Andrew U. Frank"     # create dir in ExampleTesting
    # filename must be homedir + program name (in Foundation) - hidden
    # fixed in testharness
#    uploadServer: "sgg.gerastree.at"
    
    # needs link in resources/templates to themes/templates
localhostPort: 3000

#quotes: True 
# css :
#     - /templates/static/style.css  # relative to root of site - so called absolute
#     - /templates/static/menu.css 
#   values taken from page3/yaml

# content for landing page
settingsAuthor : Author of Settings 
settingsDate: 2019-01-01

siteHeader : 
    sitename : siteName3
    byline : siteByLine3 
    # banner: /resources/templates/img/symmetricGeras2.jpg  
    banner: /resources/templates/img/DSC04809.JPG
    bannerCaption: "Ruhiger Sommer im Garten in Geras"
    # keywords ??

menuitems:
    menuNav:
     # navlink must not start with /
      - navlink: Blog/index.html
        navtext: Blog
      - navlink : PublicationList/index.html
        navtext : Publications
      # - navlink : SSGdesign/index.html
      #   navtext : SSG Documentation  

# the menu is for the navigation part

