# settings3.yaml -- the basic setup of the test site

# goes into SiteLayout
storage:
    themeDir:  /home/frank/Workspace11/ssg/docs/theme
    doughDir: /home/frank/Workspace11/ssg/docs/site/dough
    bakedDir: /home/frank/Workspace11/ssg/docs/site/baked
    reportFile: /home/frank/ssgReport.txt
    testDir: /home/frank/.ssg 
    masterTemplateFile: master5.dtpl  #in themeDir
    # create dir in ExampleTesting
    # filename must be homedir + program name (in Foundation) - hidden
    # fixed in testharness
#    uploadServer: "sgg.gerastree.at"
    
localhostPort: 3000

#quotes: True 
# css :
#     - /templates/static/style.css  # relative to root of site - so called absolute
#     - /templates/static/menu.css 
#   values taken from page3/yaml

# content for landing page
settingsAuthor : Author of Settings 
settingsDate: 2019-01-01
settings : 
    sitename : siteName
    byline : siteByLine 
    banner: /templates/img/symmetricGeras2.jpg

menuitems:
    menuNav:
     - navlink: Blog/index.html
     # navlink must not start with /
       navtext: Blog
     - navlink : PublicationList/index.html
       navtext : Publications
    #  - navlink : SSGdesign/index.html
      #  navtext : SSG Documentation  

# the menu is for the navigation part

