name: ssg
version: 0.0.4.4
synopsis: a static site generator using shake and pandoc
description: | 
  A static site generator from pandoc and other available packages on Hackage (e.g. shake, twitch, scotty), influenced by Chris Penner's [slick](https://github.com/ChrisPenner/slick#readme). It uses files to manage data to permit version management with git. Page appearances are directed with YAML and internally data is structured with JSON, for each page a PDF file is produced to allow regular looking prints. Index pages are automatically created.
    
category: Development Web

license-file: LICENSE
author: Andrew U. Frank (frank@geoinfo.tuwien.ac.at)
github:  frank/ssg

spec-version: 0.30.0 # the hpack version minimally required 
extra-source-files:
  - changelog.md
  - README.md

ghc-options: 
    -Wall
    -fno-warn-unused-binds 
    -fno-warn-deprecations 
    -fno-warn-unused-do-bind 
    -fno-warn-missing-signatures
    -fno-warn-orphans
    -fno-warn-type-defaults 
    -fno-warn-unused-matches 
    -fno-warn-warnings-deprecations 
    -fno-warn-missing-methods 
dependencies: 
    - base  
    - uniformBase  
    -  uniform-json
    -  uniform-shake
    - uniform-convenience # from u2to
    - uniform-cmdLineArgs # from u2to
    - uniform-watch 
    - uniform-webserver  # - shake
    - data-default
    - uniform-pandoc 
    - uniform-latex2pdf 
    # -- - uniform-ftp

library:
  source-dirs: 
      - src 

executables:   # file names wiwth lowercase to avoid forcing Main
  ssgbake:
    main: ssgBake.hs
    source-dirs: app
    dependencies: 
    - ssg
    # - uniform-webserver
    # - uniform-convenience
  
  # ssgcheck:
  #   main: ssgCheck.hs
  #   source-dirs: app
  #   dependencies:
  #       ssg

  # ssgPrepareTest:  #wohl nicht notwendig, verwende die von ssgbake gebauten werte
  #   main: prepareTest.hs
  #   source-dirs: app
  #   other-modules:
  #     - Lib.CmdLineArgs
  #     -  Foundational.Foundation
  #     -  Foundational.MetaPage
  #     -  ShakeBake.ReadSettingFile
  #     -  Foundational.Filetypes4sites
  #   dependencies:
  #       ssg

 
tests:
  ssgTest:
    main: testing.hs
    source-dirs: tests

    ghc-options: 
      -threaded 
      -rtsopts 
      -with-rtsopts=-N    
    dependencies:
      - HTF
      - quickcheck-text
      # - uniform-strings
      # - uniform-http
      - uniformBase
      - ssg
      # - shake  # from error
    
