name: ssg
version: 0.0.4.3
synopsis: a static site generator using shake and pandoc
description: a static site generator
    version 0.0.2.0  used for myhomepage  - fixes
    0.0.2.1 add check for all pages, study content pdf, tex
    0.0.3.0 copy all structure (exclude with DNB)
    0.0.3.1 change to 15.13 (pandoc not resolvable)
    0.0.4   start with hpack, lts-16.0 (8.8.)
    0.0.4.2 recovering from 2000, rebuild Docrep, restricted use of JSON to docrep processing, moved the uniform-modules for blog inside SSG
    0.0.4.3 clean up, then 
    
category: Development

license-file: LICENSE
author: Andrew U. Frank (frank@geoinfo.tuwien.ac.at)
github:  frank/ssg

spec-version: 0.30.0 # the hpack version minimally required 
extra-source-files:
  - changelog.md
  - README.md

ghc-options: 
    -Wall
    -fno-warn-unused-binds 
    -fno-warn-unused-imports 
    -fno-warn-deprecations 
    -fno-warn-unused-do-bind 
    -fno-warn-missing-signatures
    -fno-warn-orphans
    -fno-warn-type-defaults 
    -fno-warn-dodgy-imports 
    -fno-warn-unused-matches 
    -fno-warn-warnings-deprecations 
    -fno-warn-duplicate-exports
    -fno-warn-missing-methods 
dependencies: 
    - base  
    - uniformBase 
    -  uniform-json
    # -  uniform-strings  
    -  uniform-shake
    - shake
    - path-io
    - pipes
    - containers
    - aeson
    - data-default
   
    # not in uniformBase:
    - uniform-pandoc  
    - pandoc 
    - doclayout
    - doctemplates
    - pandoc-citeproc
    - lens-aeson
    - lens 
    - pandoc-types
    - bibtex
    - aeson 
    - parsec
    # - containers
    - process

    - uniform-convenience 
    - uniform-watch 
    - uniform-webserver
    # -- - uniform-ftp

    - optparse-applicative
    - optparse-generic
  # -- - pandoc-types

library:
  source-dirs: 
      - src 
  

  # other: watch 
 
executables:  
  ssgbake:
    main: ssgBake.hs
    source-dirs: app
    dependencies: 
    - ssg
    - uniform-webserver
    - uniform-convenience
  
  ssgcheck:
    main: ssgCheck.hs
    source-dirs: app
    dependencies:
        ssg
# tests:
#   test:
#     main: Testing.hs
#     source-dirs: tests
