name: ssg
version: 0.0.4.10
synopsis: a static site generator using shake and pandoc
description: | 
  A static site generator from pandoc and other available packages on Hackage (e.g. shake, twitch, scotty), influenced by Chris Penner's [slick](https://github.com/ChrisPenner/slick#readme). It uses files to manage data to permit version management with git. Page appearances are directed with YAML and internally data is structured with JSON, for each page a PDF file is produced to allow regular looking prints. Index pages are automatically created.


# installation needed:
#     texlive-luatex
# then run at least once the texstudio with lualatex as compiler

category: Development Web

# run with hpack before cabal build

license-file: LICENSE
author: Andrew U. Frank (frank@geoinfo.tuwien.ac.at)
github:  frank/ssg

spec-version: 0.30.0 # the hpack version minimally required 
extra-source-files:
  - changelog.md
  - README.md
# language: Haskell2010 is default

# ghc-options: 
#     -Wall
#     -fno-warn-unused-binds 
#     -fno-warn-deprecations 
#     -fno-warn-unused-do-bind 
#     -fno-warn-unused-imports
#     -fno-warn-missing-signatures
#     -fno-warn-orphans
#     -fno-warn-type-defaults 
#     -fno-warn-unused-matches 
#     -fno-warn-warnings-deprecations   
#     -fno-warn-missing-methods 
#     -fno-warn-missing-home-modules
#     -fno-warn-duplicate-exports 
other-extensions:  # besides the automatically Haskell2010
# has no effect...
    # - DeriveGeneric
    # - FlexibleContexts 
    # - FlexibleInstances 
    # - MultiParamTypeClasses 
    - OverloadedStrings
    # - ScopedTypeVariables 
    # - GeneralizedNewtypeDeriving 
    # - RecordWildCards 
    
    #  -XDeriveGeneric
    # -XFlexibleContexts
    # -XFlexibleInstances
    # -XMultiParamTypeClasses
    # -XOverloadedStrings
    # -XScopedTypeVariables
    # -XGeneralizedNewtypeDeriving
    # -XRecordWildCards
  # do not always include: 
  # -XConstraintKinds
    # -XDeriveAnyClass
      # -XDoAndIfThenElse
    # -XDuplicateRecordFields
    # -XTypeFamilies
    # -XUndecidableInstances  

dependencies: 
    - base  > 4.7 && < 5
    - uniformBase  == 0.1.4
    - uniform-json
    -  uniform-shake >= 0.0.1.2
    - uniform-http
    # - uniform-convenience # from u2to
    # - uniform-startapp # from u2to - replace with startProg in uniform-error 
    - uniform-cmdLineArgs # from u2to
    - uniform-watch 
    - uniform-webserver  # - shake
    - uniform-pandoc >= 0.0.2.4 # from u4blog
    - uniform-latex2pdf >=0.0.1.1
    # - uniform-fileio
    # - pandoc-types  # needed? 
    # -- - uniform-ftp
    # - aeson 
    # - optparse-applicative -- does not allow value in cmdlineargs
    # - data-default
    - data-default-class # for default values, move down 
    - dir-traverse # for checkprocess
    - deepseq
    - pandoc-sidenote

library:
  source-dirs: 
      - src 

executables:   # file names wiwth lowercase to avoid forcing Main
  ssgbake:
    main: ssgBake.hs
    source-dirs: app
    dependencies: 
    - ssg
    # - uniform-webserver
    # - uniform-convenience
  
  ssgcheck:  # breaks on first error and indicates where this is. fix and retry!
    main: ssgCheck.hs
    source-dirs: app
    dependencies:
      - ssg
      # - dir-traverse

  # ssgPrepareTest:  #wohl nicht notwendig, verwende die von ssgbake gebauten werte
  #   main: prepareTest.hs
  #   source-dirs: app
  #   other-modules:
  #     - Lib.CmdLineArgs
  #     -  Foundational.Foundation
  #     -  Foundational.MetaPage
  #     -  ShakeBake.ReadSettingFile
  #     -  Foundational.Filetypes4sites
  #   dependencies:
  #       ssg

 
# tests:
#   ssgTest:
#     main: testing.hs
#     source-dirs: tests

#     ghc-options: 
#       -threaded 
#       -rtsopts 
#       -with-rtsopts=-N    
#     dependencies:
#       - HTF
#       - quickcheck-text
#       # - uniform-strings
#       # - uniform-http
#       - uniformBase == 0.1.2
#       - ssg
#       # - shake  # from error
    
