
# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
#
# resolver: lts-18.28
# for ghc 8.10.7
resolver: lts-19.16 # for ghc 9.0.2 newest lts
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
#
# The location of a snapshot can be provided as a file or url. Stack assumes
# a snapshot provided as a file might change, whereas a url resource does not.
#
# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
# resolver:
  # url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/5.yaml

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
packages:
- .
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#
extra-deps:

- ../uBase/uniformBase
- ../uBase/uniform-algebras
- ../uBase/uniform-error
- ../uBase/uniform-fileio
- ../uBase/uniform-strings
- ../uBase/uniform-time

- ../u4blog/uniform-http
- ../u4blog/uniform-json  # braucht version 0.0.6.1 for lts-19.16
- ../u4blog/uniform-latex2pdf
- ../u4blog/uniform-pandoc
- ../u4blog/uniform-shake
- ../u4blog/uniform-watch
- ../u4blog/uniform-webserver

- ../u2to/uniform-cmdLineArgs
- ../u2to/uniform-convenience

# for 9.0.2
- dir-traverse-0.2.3.0@sha256:adcc128f201ff95131b15ffe41365dc99c50dc3fa3a910f021521dc734013bfa,2137
- pandoc-sidenote-0.22.1.0@sha256:44a4e9db8dcbd93fdc8b1a6e038b4d6402cace3b5f1bd3532ebd7e4e3ed0f2a2,1732
- test-invariant-0.4.5.0@sha256:d1aa6b61e0057a4065eeff3286208e947a0b44c6a2186210399f5e5e7fb0d0dd,1902
- twitch-0.1.7.2@sha256:146a887da4d2d21e489ff823a6058add40c1f9c5ee8e0d00356b497092c9c624,2988


# - ../uniformWorking/uniformSources/uniform-strings
# - ../uniformWorking/uniformSources/uniform-algebras
# # - ../uniformWorking/uniformSources/uniform-convenience
# - ../uniformWorking/uniformSources/uniform-error
# - ../uniformWorking/uniformSources/uniform-time
# - ../uniformWorking/uniformSources/uniform-fileio
# # - ../uniformWorking/uniformSources/uniform-http
# - ../uniformWorking/uniformSources/uniform-json
# # - ../uniformWorking/uniformSources/uniform-pandoc
# # - ../fromOthersInstalled/bibtex  # has a fix compared to hackage, see cabal
# - ../uniformWorking/uniformSources/uniform-cmdLineArgs
# - test-invariant-0.4.5.0   
# # - twitch-0.1.7.2
# - dir-traverse-0.2.3.0@sha256:adcc128f201ff95131b15ffe41365dc99c50dc3fa3a910f021521dc734013bfa,2137
# - pandoc-sidenote-0.22.1.0@sha256:44a4e9db8dcbd93fdc8b1a6e038b4d6402cace3b5f1bd3532ebd7e4e3ed0f2a2,1732
# - aeson-2.0.3.0
# - twitch-0.1.7.2@sha256:146a887da4d2d21e489ff823a6058add40c1f9c5ee8e0d00356b497092c9c624,2988
# - OneTuple-0.3.1@sha256:a848c096c9d29e82ffdd30a9998aa2931cbccb3a1bc137539d80f6174d31603e,2262
# - attoparsec-0.14.4@sha256:79584bdada8b730cb5138fca8c35c76fbef75fc1d1e01e6b1d815a5ee9843191,5810
# - generically-0.1@sha256:16d54a08bcdf708395c2200a28ffcba55e90479dc96ed617dbb94f0411f7a7af,1024
# - hashable-1.4.0.2@sha256:0cddd0229d1aac305ea0404409c0bbfab81f075817bd74b8b2929eff58333e55,5005
# - semialign-1.2.0.1@sha256:2ab22ab4f7e67028a745e549ae49f1ddecbd83e62d7e6ecce4ab0685410da536,2836
# - text-short-0.1.5@sha256:962c6228555debdc46f758d0317dea16e5240d01419b42966674b08a5c3d8fa6,3498
# - time-compat-1.9.6.1@sha256:42d8f2e08e965e1718917d54ad69e1d06bd4b87d66c41dc7410f59313dba4ed1,5033


ghc-options:
  "$everything": -haddock
  "$everything": -Wno-deprecations