flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uniform/uniform-strings
- ../uniform/uniform-algebras
- ../uniform/uniform-convenience
- ../uniform/uniform-cmdLineArgs
- ../uniform/uniform-fileio
# - ../uniform/uniform-ftp
- ../uniform/uniform-time
- ../uniform/uniform-error
- ../uniform/uniform-json
- ../uniform/uniform-pandoc
- ../uniform/uniform-shake
- ../uniform/uniform-watch
- ../uniform/uniform-webserver
- ../fromOthersInstalled/bibtex
# - ../fromOthersInstalled/path
# - ../fromOthersInstalled/path-io
#- ../fromOthersInstalled/pretty-show
# - ../fromOthers/shake-path

extra-deps:
  # for 16.0
- shake-0.17.5
- test-invariant-0.4.5.0@sha256:d1aa6b61e0057a4065eeff3286208e947a0b44c6a2186210399f5e5e7fb0d0dd,1902
- twitch-0.1.7.2@sha256:146a887da4d2d21e489ff823a6058add40c1f9c5ee8e0d00356b497092c9c624,2988

#for 15.13
# - shake-0.17.1
# - test-invariant-0.4.5.0@sha256:d1aa6b61e0057a4065eeff3286208e947a0b44c6a2186210399f5e5e7fb0d0dd,1902
# - twitch-0.1.7.2@sha256:146a887da4d2d21e489ff823a6058add40c1f9c5ee8e0d00356b497092c9c624,2988
# for 13.19
# - test-invariant-0.4.5.0
# - twitch-0.1.7.2
# - yaml-union-0.0.3
# - shake-ext-3.1.0.0
# - ftphs-1.0.9.2
# - shake-path-0.0.0.1
# - scholdoc-types-0.1.3.1
# - spawn-0.3
# - fsutils-0.1.2
#- path-0.7.0@sha256:f1629c247f4673650046a690f07958343abc63adc035b451610a550a8ac6055e,3177

resolver: lts-16.0 # 15.13 # 13.12  # 26 seems to have a problem with pandoc
