flags: {}
extra-package-dbs: []
packages:
- '.'
- ../uniform/uniform-strings
- ../uniform/uniform-algebras
- ../uniform/uniform-convenience
- ../uniform/uniform-cmdLineArgs
- ../uniform/uniform-fileio
- ../uniform/uniform-ftp
- ../uniform/uniform-time
- ../uniform/uniform-error
- ../uniform/uniform-json
- ../uniform/uniform-pandoc
- ../uniform/uniform-shake
- ../uniform/uniform-watch
- ../uniform/uniform-webserver
- ../fromOthersInstalled/bibtex
- ../fromOthersInstalled/path
- ../fromOthersInstalled/path-io
#- ../fromOthers/pretty-show
# - ../fromOthers/shake-path

extra-deps:
- test-invariant-0.4.5.0
- twitch-0.1.7.2
- yaml-union-0.0.3
- shake-ext-3.1.0.0
- ftphs-1.0.9.2
# - shake-path-0.0.0.1
# - scholdoc-types-0.1.3.1
# - spawn-0.3
# - fsutils-0.1.2
resolver: lts-13.12  # 26 seems to have a problem with pandoc
